// AUTO-GENERATED by mcp__supabase__generate_typescript_types
// project: kintai (zjjbfffhbobwwxyvdszl), generated 2026-05-22 (Loop 2)
// 上書き再生成は Engineer A の手作業で実施。手動編集禁止。

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      attendance_records: {
        Row: {
          break_end: string | null
          break_start: string | null
          clock_in: string | null
          clock_out: string | null
          created_at: string | null
          date: string
          id: string
          note: string | null
          store_id: string | null
          tenant_id: string
          total_work_minutes: number | null
          user_id: string
        }
        Insert: {
          break_end?: string | null
          break_start?: string | null
          clock_in?: string | null
          clock_out?: string | null
          created_at?: string | null
          date: string
          id?: string
          note?: string | null
          store_id?: string | null
          tenant_id: string
          total_work_minutes?: number | null
          user_id: string
        }
        Update: {
          break_end?: string | null
          break_start?: string | null
          clock_in?: string | null
          clock_out?: string | null
          created_at?: string | null
          date?: string
          id?: string
          note?: string | null
          store_id?: string | null
          tenant_id?: string
          total_work_minutes?: number | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "attendance_records_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attendance_records_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      breaks: {
        Row: {
          attendance_record_id: string
          created_at: string | null
          end_time: string | null
          id: string
          start_time: string
        }
        Insert: {
          attendance_record_id: string
          created_at?: string | null
          end_time?: string | null
          id?: string
          start_time: string
        }
        Update: {
          attendance_record_id?: string
          created_at?: string | null
          end_time?: string | null
          id?: string
          start_time?: string
        }
        Relationships: [
          {
            foreignKeyName: "breaks_attendance_record_id_fkey"
            columns: ["attendance_record_id"]
            isOneToOne: false
            referencedRelation: "attendance_records"
            referencedColumns: ["id"]
          },
        ]
      }
      correction_requests: {
        Row: {
          attendance_record_id: string | null
          created_at: string | null
          date: string
          id: string
          reason: string
          request_type: string | null
          requested_clock_in: string | null
          requested_clock_out: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          status: string | null
          store_id: string | null
          tenant_id: string
          user_id: string
        }
        Insert: {
          attendance_record_id?: string | null
          created_at?: string | null
          date: string
          id?: string
          reason: string
          request_type?: string | null
          requested_clock_in?: string | null
          requested_clock_out?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string | null
          store_id?: string | null
          tenant_id: string
          user_id: string
        }
        Update: {
          attendance_record_id?: string | null
          created_at?: string | null
          date?: string
          id?: string
          reason?: string
          request_type?: string | null
          requested_clock_in?: string | null
          requested_clock_out?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string | null
          store_id?: string | null
          tenant_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "correction_requests_attendance_record_id_fkey"
            columns: ["attendance_record_id"]
            isOneToOne: false
            referencedRelation: "attendance_records"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "correction_requests_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "correction_requests_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      invite_code_stores: {
        Row: {
          created_at: string
          id: string
          store_id: string
          tenant_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          store_id: string
          tenant_id: string
        }
        Update: {
          created_at?: string
          id?: string
          store_id?: string
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "invite_code_stores_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invite_code_stores_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      leave_requests: {
        Row: {
          created_at: string | null
          date: string
          id: string
          leave_type: string
          reason: string | null
          review_note: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          status: string
          store_id: string | null
          tenant_id: string
          user_id: string
        }
        Insert: {
          created_at?: string | null
          date: string
          id?: string
          leave_type: string
          reason?: string | null
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
          store_id?: string | null
          tenant_id: string
          user_id: string
        }
        Update: {
          created_at?: string | null
          date?: string
          id?: string
          leave_type?: string
          reason?: string | null
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
          store_id?: string | null
          tenant_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "leave_requests_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leave_requests_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      member_store_payrolls: {
        Row: {
          created_at: string
          hourly_rate: number | null
          id: string
          monthly_salary: number | null
          night_shift_rate_multiplier: number
          pay_type: string
          store_id: string
          tenant_id: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          hourly_rate?: number | null
          id?: string
          monthly_salary?: number | null
          night_shift_rate_multiplier?: number
          pay_type: string
          store_id: string
          tenant_id: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          hourly_rate?: number | null
          id?: string
          monthly_salary?: number | null
          night_shift_rate_multiplier?: number
          pay_type?: string
          store_id?: string
          tenant_id?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "member_store_payrolls_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "member_store_payrolls_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          body: string | null
          created_at: string
          id: string
          link: string | null
          read_at: string | null
          tenant_id: string
          title: string
          type: string
          user_id: string
        }
        Insert: {
          body?: string | null
          created_at?: string
          id?: string
          link?: string | null
          read_at?: string | null
          tenant_id: string
          title: string
          type: string
          user_id: string
        }
        Update: {
          body?: string | null
          created_at?: string
          id?: string
          link?: string | null
          read_at?: string | null
          tenant_id?: string
          title?: string
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      payroll_run_items: {
        Row: {
          display_name: string
          hourly_rate: number
          id: string
          monthly_salary: number
          night_minutes: number
          normal_minutes: number
          pay_type: string
          payment: number
          run_id: string
          user_id: string
          work_days: number
        }
        Insert: {
          display_name: string
          hourly_rate?: number
          id?: string
          monthly_salary?: number
          night_minutes?: number
          normal_minutes?: number
          pay_type: string
          payment?: number
          run_id: string
          user_id: string
          work_days?: number
        }
        Update: {
          display_name?: string
          hourly_rate?: number
          id?: string
          monthly_salary?: number
          night_minutes?: number
          normal_minutes?: number
          pay_type?: string
          payment?: number
          run_id?: string
          user_id?: string
          work_days?: number
        }
        Relationships: [
          {
            foreignKeyName: "payroll_run_items_run_id_fkey"
            columns: ["run_id"]
            isOneToOne: false
            referencedRelation: "payroll_runs"
            referencedColumns: ["id"]
          },
        ]
      }
      payroll_runs: {
        Row: {
          close_day: number
          finalized_at: string
          finalized_by: string | null
          id: string
          mode: string
          note: string | null
          period_end: string
          period_start: string
          store_id: string | null
          target_month: string
          tenant_id: string
          total_payment: number
        }
        Insert: {
          close_day: number
          finalized_at?: string
          finalized_by?: string | null
          id?: string
          mode: string
          note?: string | null
          period_end: string
          period_start: string
          store_id?: string | null
          target_month: string
          tenant_id: string
          total_payment?: number
        }
        Update: {
          close_day?: number
          finalized_at?: string
          finalized_by?: string | null
          id?: string
          mode?: string
          note?: string | null
          period_end?: string
          period_start?: string
          store_id?: string | null
          target_month?: string
          tenant_id?: string
          total_payment?: number
        }
        Relationships: [
          {
            foreignKeyName: "payroll_runs_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payroll_runs_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      projects: {
        Row: {
          created_at: string
          created_by: string
          description: string | null
          id: string
          name: string
          status: string
          store_id: string | null
          tenant_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by: string
          description?: string | null
          id?: string
          name: string
          status?: string
          store_id?: string | null
          tenant_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string
          description?: string | null
          id?: string
          name?: string
          status?: string
          store_id?: string | null
          tenant_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "projects_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "projects_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      shift_preferences: {
        Row: {
          created_at: string | null
          date: string
          end_time: string | null
          id: string
          note: string | null
          preference_type: string
          start_time: string | null
          status: string
          store_id: string
          tenant_id: string
          user_id: string
        }
        Insert: {
          created_at?: string | null
          date: string
          end_time?: string | null
          id?: string
          note?: string | null
          preference_type: string
          start_time?: string | null
          status?: string
          store_id: string
          tenant_id: string
          user_id: string
        }
        Update: {
          created_at?: string | null
          date?: string
          end_time?: string | null
          id?: string
          note?: string | null
          preference_type?: string
          start_time?: string | null
          status?: string
          store_id?: string
          tenant_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "shift_preferences_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "shift_preferences_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      shift_presets: {
        Row: {
          created_at: string | null
          end_time: string
          id: string
          name: string
          sort_order: number | null
          start_time: string
          store_id: string | null
          tenant_id: string
        }
        Insert: {
          created_at?: string | null
          end_time: string
          id?: string
          name: string
          sort_order?: number | null
          start_time: string
          store_id?: string | null
          tenant_id: string
        }
        Update: {
          created_at?: string | null
          end_time?: string
          id?: string
          name?: string
          sort_order?: number | null
          start_time?: string
          store_id?: string | null
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "shift_presets_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "shift_presets_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      shift_submission_deadlines: {
        Row: {
          created_at: string
          created_by: string | null
          deadline_at: string
          id: string
          store_id: string
          target_month: string
          tenant_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          deadline_at: string
          id?: string
          store_id: string
          target_month: string
          tenant_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          deadline_at?: string
          id?: string
          store_id?: string
          target_month?: string
          tenant_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "shift_submission_deadlines_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "shift_submission_deadlines_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      shifts: {
        Row: {
          created_at: string | null
          date: string
          end_time: string
          id: string
          note: string | null
          original_end_time: string | null
          original_start_time: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          start_time: string
          status: string
          store_id: string
          tenant_id: string
          tentative_approved_at: string | null
          tentative_approved_by: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          date: string
          end_time: string
          id?: string
          note?: string | null
          original_end_time?: string | null
          original_start_time?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          start_time: string
          status?: string
          store_id: string
          tenant_id: string
          tentative_approved_at?: string | null
          tentative_approved_by?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          date?: string
          end_time?: string
          id?: string
          note?: string | null
          original_end_time?: string | null
          original_start_time?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          start_time?: string
          status?: string
          store_id?: string
          tenant_id?: string
          tentative_approved_at?: string | null
          tentative_approved_by?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "shifts_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "shifts_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      store_members: {
        Row: {
          created_at: string | null
          id: string
          is_manager: boolean
          is_primary: boolean | null
          member_id: string
          store_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          is_manager?: boolean
          is_primary?: boolean | null
          member_id: string
          store_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          is_manager?: boolean
          is_primary?: boolean | null
          member_id?: string
          store_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "store_members_member_id_fkey"
            columns: ["member_id"]
            isOneToOne: false
            referencedRelation: "tenant_members"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "store_members_member_id_fkey"
            columns: ["member_id"]
            isOneToOne: false
            referencedRelation: "tenant_members_visible"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "store_members_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      stores: {
        Row: {
          created_at: string | null
          id: string
          name: string
          tenant_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          name: string
          tenant_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          name?: string
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "stores_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      tasks: {
        Row: {
          assignee_user_id: string | null
          completed_at: string | null
          created_at: string
          created_by: string
          description: string | null
          due_date: string | null
          id: string
          priority: number
          project_id: string | null
          status: string
          store_id: string | null
          tenant_id: string
          title: string
          updated_at: string
        }
        Insert: {
          assignee_user_id?: string | null
          completed_at?: string | null
          created_at?: string
          created_by: string
          description?: string | null
          due_date?: string | null
          id?: string
          priority?: number
          project_id?: string | null
          status?: string
          store_id?: string | null
          tenant_id: string
          title: string
          updated_at?: string
        }
        Update: {
          assignee_user_id?: string | null
          completed_at?: string | null
          created_at?: string
          created_by?: string
          description?: string | null
          due_date?: string | null
          id?: string
          priority?: number
          project_id?: string | null
          status?: string
          store_id?: string | null
          tenant_id?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "tasks_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      tenant_invite_code_stores: {
        Row: {
          invite_code_id: string
          sort_order: number
          store_id: string
        }
        Insert: {
          invite_code_id: string
          sort_order?: number
          store_id: string
        }
        Update: {
          invite_code_id?: string
          sort_order?: number
          store_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tenant_invite_code_stores_invite_code_id_fkey"
            columns: ["invite_code_id"]
            isOneToOne: false
            referencedRelation: "tenant_invite_codes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tenant_invite_code_stores_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      tenant_invite_codes: {
        Row: {
          code: string
          created_at: string
          created_by: string
          expires_at: string | null
          id: string
          label: string | null
          max_uses: number | null
          revoked_at: string | null
          tenant_id: string
          used_count: number
        }
        Insert: {
          code: string
          created_at?: string
          created_by: string
          expires_at?: string | null
          id?: string
          label?: string | null
          max_uses?: number | null
          revoked_at?: string | null
          tenant_id: string
          used_count?: number
        }
        Update: {
          code?: string
          created_at?: string
          created_by?: string
          expires_at?: string | null
          id?: string
          label?: string | null
          max_uses?: number | null
          revoked_at?: string | null
          tenant_id?: string
          used_count?: number
        }
        Relationships: [
          {
            foreignKeyName: "tenant_invite_codes_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      tenant_members: {
        Row: {
          created_at: string | null
          display_name: string
          hourly_rate: number | null
          id: string
          is_parttime: boolean
          legal_name: string | null
          monthly_salary: number | null
          night_shift_enabled: boolean | null
          onboarded_at: string | null
          paid_leave_days: number | null
          pay_type: string
          role: string | null
          role_id: string | null
          tenant_id: string
          user_id: string
        }
        Insert: {
          created_at?: string | null
          display_name: string
          hourly_rate?: number | null
          id?: string
          is_parttime?: boolean
          legal_name?: string | null
          monthly_salary?: number | null
          night_shift_enabled?: boolean | null
          onboarded_at?: string | null
          paid_leave_days?: number | null
          pay_type?: string
          role?: string | null
          role_id?: string | null
          tenant_id: string
          user_id: string
        }
        Update: {
          created_at?: string | null
          display_name?: string
          hourly_rate?: number | null
          id?: string
          is_parttime?: boolean
          legal_name?: string | null
          monthly_salary?: number | null
          night_shift_enabled?: boolean | null
          onboarded_at?: string | null
          paid_leave_days?: number | null
          pay_type?: string
          role?: string | null
          role_id?: string | null
          tenant_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tenant_members_role_id_fkey"
            columns: ["role_id"]
            isOneToOne: false
            referencedRelation: "tenant_roles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tenant_members_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      tenant_roles: {
        Row: {
          color: string | null
          created_at: string
          default_hourly_rate: number | null
          default_monthly_salary: number | null
          id: string
          name: string
          sort_order: number
          tenant_id: string
        }
        Insert: {
          color?: string | null
          created_at?: string
          default_hourly_rate?: number | null
          default_monthly_salary?: number | null
          id?: string
          name: string
          sort_order?: number
          tenant_id: string
        }
        Update: {
          color?: string | null
          created_at?: string
          default_hourly_rate?: number | null
          default_monthly_salary?: number | null
          id?: string
          name?: string
          sort_order?: number
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tenant_roles_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      tenants: {
        Row: {
          created_at: string | null
          default_deadline_day: number | null
          deleted_at: string | null
          id: string
          invite_code: string
          invite_code_expires_at: string | null
          invite_code_max_uses: number | null
          invite_code_used_count: number
          name: string
          owner_id: string
          payroll_close_day: number
        }
        Insert: {
          created_at?: string | null
          default_deadline_day?: number | null
          deleted_at?: string | null
          id?: string
          invite_code: string
          invite_code_expires_at?: string | null
          invite_code_max_uses?: number | null
          invite_code_used_count?: number
          name: string
          owner_id: string
          payroll_close_day?: number
        }
        Update: {
          created_at?: string | null
          default_deadline_day?: number | null
          deleted_at?: string | null
          id?: string
          invite_code?: string
          invite_code_expires_at?: string | null
          invite_code_max_uses?: number | null
          invite_code_used_count?: number
          name?: string
          owner_id?: string
          payroll_close_day?: number
        }
        Relationships: []
      }
    }
    Views: {
      tenant_members_visible: {
        Row: {
          created_at: string | null
          display_name: string | null
          hourly_rate: number | null
          id: string | null
          legal_name: string | null
          monthly_salary: number | null
          night_shift_enabled: boolean | null
          onboarded_at: string | null
          paid_leave_days: number | null
          pay_type: string | null
          role: string | null
          role_id: string | null
          tenant_id: string | null
          user_id: string | null
        }
        Insert: {
          created_at?: string | null
          display_name?: string | null
          hourly_rate?: number | null
          id?: string | null
          legal_name?: never
          monthly_salary?: number | null
          night_shift_enabled?: boolean | null
          onboarded_at?: string | null
          paid_leave_days?: number | null
          pay_type?: string | null
          role?: string | null
          role_id?: string | null
          tenant_id?: string | null
          user_id?: string | null
        }
        Update: {
          created_at?: string | null
          display_name?: string | null
          hourly_rate?: number | null
          id?: string | null
          legal_name?: never
          monthly_salary?: number | null
          night_shift_enabled?: boolean | null
          onboarded_at?: string | null
          paid_leave_days?: number | null
          pay_type?: string | null
          role?: string | null
          role_id?: string | null
          tenant_id?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "tenant_members_role_id_fkey"
            columns: ["role_id"]
            isOneToOne: false
            referencedRelation: "tenant_roles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tenant_members_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      approve_shift_final: {
        Args: { p_shift_id: string }
        Returns: {
          created_at: string | null
          date: string
          end_time: string
          id: string
          note: string | null
          original_end_time: string | null
          original_start_time: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          start_time: string
          status: string
          store_id: string
          tenant_id: string
          tentative_approved_at: string | null
          tentative_approved_by: string | null
          user_id: string
        }
        SetofOptions: {
          from: "*"
          to: "shifts"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      approve_shift_tentative: {
        Args: { p_shift_id: string }
        Returns: {
          created_at: string | null
          date: string
          end_time: string
          id: string
          note: string | null
          original_end_time: string | null
          original_start_time: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          start_time: string
          status: string
          store_id: string
          tenant_id: string
          tentative_approved_at: string | null
          tentative_approved_by: string | null
          user_id: string
        }
        SetofOptions: {
          from: "*"
          to: "shifts"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      approve_store_shifts_final: {
        Args: { p_store_id: string; p_tenant_id: string }
        Returns: {
          approved_count: number
          approved_ids: string[]
        }[]
      }
      bulk_assign_tasks: {
        Args: { p_assignee: string; p_task_ids: string[] }
        Returns: {
          assignee_user_id: string | null
          completed_at: string | null
          created_at: string
          created_by: string
          description: string | null
          due_date: string | null
          id: string
          priority: number
          project_id: string | null
          status: string
          store_id: string | null
          tenant_id: string
          title: string
          updated_at: string
        }[]
        SetofOptions: {
          from: "*"
          to: "tasks"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      cancel_shift_tentative: {
        Args: { p_shift_id: string }
        Returns: {
          created_at: string | null
          date: string
          end_time: string
          id: string
          note: string | null
          original_end_time: string | null
          original_start_time: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          start_time: string
          status: string
          store_id: string
          tenant_id: string
          tentative_approved_at: string | null
          tentative_approved_by: string | null
          user_id: string
        }
        SetofOptions: {
          from: "*"
          to: "shifts"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      complete_onboarding: {
        Args: {
          p_display_name: string
          p_legal_name: string
          p_tenant_id: string
        }
        Returns: undefined
      }
      complete_task: {
        Args: { p_task_id: string }
        Returns: {
          assignee_user_id: string | null
          completed_at: string | null
          created_at: string
          created_by: string
          description: string | null
          due_date: string | null
          id: string
          priority: number
          project_id: string | null
          status: string
          store_id: string | null
          tenant_id: string
          title: string
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "tasks"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      get_my_tenant_ids: { Args: never; Returns: string[] }
      increment_invite_code_use: {
        Args: { p_tenant_id: string }
        Returns: undefined
      }
      is_my_store: { Args: { p_store_id: string }; Returns: boolean }
      is_store_manager: {
        Args: { p_store_id: string; p_tenant_id: string }
        Returns: boolean
      }
      is_tenant_managerial: { Args: { p_tenant_id: string }; Returns: boolean }
      is_tenant_owner: { Args: { tid: string }; Returns: boolean }
      is_tenant_parttime: { Args: { p_tenant_id: string }; Returns: boolean }
      issue_tenant_invite_code: {
        Args: {
          p_expires_at: string
          p_label: string
          p_max_uses: number
          p_store_ids: string[]
          p_tenant_id: string
        }
        Returns: string
      }
      join_tenant_with_invite: {
        Args: { p_display_name: string; p_invite_code: string }
        Returns: string
      }
      join_tenant_with_invite_v2: {
        Args: { p_display_name: string; p_invite_code: string }
        Returns: string
      }
      join_tenant_with_invite_v3: {
        Args: { p_display_name: string; p_invite_code: string }
        Returns: string
      }
      regenerate_invite_code_with_stores: {
        Args: {
          p_expires_at: string
          p_max_uses: number
          p_new_code: string
          p_store_ids: string[]
          p_tenant_id: string
        }
        Returns: undefined
      }
      reject_shift: {
        Args: { p_reason?: string; p_shift_id: string }
        Returns: {
          created_at: string | null
          date: string
          end_time: string
          id: string
          note: string | null
          original_end_time: string | null
          original_start_time: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          start_time: string
          status: string
          store_id: string
          tenant_id: string
          tentative_approved_at: string | null
          tentative_approved_by: string | null
          user_id: string
        }
        SetofOptions: {
          from: "*"
          to: "shifts"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      remove_tenant_member: { Args: { p_member_id: string }; Returns: string }
      reopen_task: {
        Args: { p_task_id: string }
        Returns: {
          assignee_user_id: string | null
          completed_at: string | null
          created_at: string
          created_by: string
          description: string | null
          due_date: string | null
          id: string
          priority: number
          project_id: string | null
          status: string
          store_id: string | null
          tenant_id: string
          title: string
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "tasks"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      restore_shift: {
        Args: { p_shift_id: string }
        Returns: {
          created_at: string | null
          date: string
          end_time: string
          id: string
          note: string | null
          original_end_time: string | null
          original_start_time: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          start_time: string
          status: string
          store_id: string
          tenant_id: string
          tentative_approved_at: string | null
          tentative_approved_by: string | null
          user_id: string
        }
        SetofOptions: {
          from: "*"
          to: "shifts"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      revert_shift_to_tentative: {
        Args: { p_shift_id: string }
        Returns: {
          created_at: string | null
          date: string
          end_time: string
          id: string
          note: string | null
          original_end_time: string | null
          original_start_time: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          start_time: string
          status: string
          store_id: string
          tenant_id: string
          tentative_approved_at: string | null
          tentative_approved_by: string | null
          user_id: string
        }
        SetofOptions: {
          from: "*"
          to: "shifts"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      review_correction_request: {
        Args: { p_request_id: string; p_review_status: string }
        Returns: Json
      }
      revoke_tenant_invite_code: {
        Args: { p_code_id: string }
        Returns: undefined
      }
      set_store_member_manager:
        | {
            Args: {
              p_is_manager: boolean
              p_member_id: string
              p_store_id: string
            }
            Returns: {
              created_at: string | null
              id: string
              is_manager: boolean
              is_primary: boolean | null
              member_id: string
              store_id: string
            }
            SetofOptions: {
              from: "*"
              to: "store_members"
              isOneToOne: true
              isSetofReturn: false
            }
          }
        | {
            Args: { new_is_manager: boolean; target_store_member_id: string }
            Returns: {
              created_at: string | null
              id: string
              is_manager: boolean
              is_primary: boolean | null
              member_id: string
              store_id: string
            }
            SetofOptions: {
              from: "*"
              to: "store_members"
              isOneToOne: true
              isSetofReturn: false
            }
          }
      soft_delete_tenant: { Args: { p_tenant_id: string }; Returns: undefined }
      transfer_tenant_ownership: {
        Args: { p_new_owner_user_id: string; p_tenant_id: string }
        Returns: undefined
      }
      update_invite_code_settings: {
        Args: {
          p_expires_at: string
          p_max_uses: number
          p_store_ids: string[]
          p_tenant_id: string
        }
        Returns: undefined
      }
      update_shift_time: {
        Args: {
          p_end_time: string
          p_shift_id: string
          p_start_time: string
          p_store_id?: string
        }
        Returns: {
          created_at: string | null
          date: string
          end_time: string
          id: string
          note: string | null
          original_end_time: string | null
          original_start_time: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          start_time: string
          status: string
          store_id: string
          tenant_id: string
          tentative_approved_at: string | null
          tentative_approved_by: string | null
          user_id: string
        }
        SetofOptions: {
          from: "*"
          to: "shifts"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      update_tenant_invite_code: {
        Args: {
          p_code_id: string
          p_expires_at: string
          p_label: string
          p_max_uses: number
          p_store_ids: string[]
        }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
